name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-assets:
    name: Build Assets for Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs:
      - build-assets
    steps:
      - uses: actions/checkout@master

      - name: Download previously built artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jingbh
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jingbh/zgk-avatar:latest
